- name: Play for installing and configuring the ocserv CentOS8+
  hosts: localhost
  become: true
  gather_facts: true
  
  tasks:
  - name: Install required packages
    ansible.builtin.yum:
      name: "{{ item }}"
      state: present
    with_items:
      - podman
      - epel-release
      - firewalld
      - augeas-libs
      - python-pip
  
  - name: Install and upgrade pip
    ansible.builtin.pip:
      name: pip
      extra_args: --upgrade
      executable: pip3

  - name: Install bottle python package
    ansible.builtin.pip:
      name: certbot

  - name: Create a symbolic link
    ansible.builtin.file:
      src: /opt/certbot/bin/certbot
      dest: /usr/bin/certbot
      owner: root
      group: root
      state: link
  
  - name: Install ocserv
    ansible.builtin.yum:
      name: ocserv
      state: present

  - name: Set a hostname
    ansible.builtin.hostname:
      name: "{{ ocserv_dns_name }}"
      use: systemd

  - name: Set sysctl port-forward
    ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: true
      state: present
      reload: true

  - name: Set sysctl disable IPv6
    ansible.posix.sysctl:
      name: net.ipv6.conf.all.disable_ipv6
      value: '1'
      sysctl_set: true
      state: present
      reload: true

  - name: Auth to dyn-dns provider
    ansible.builtin.shell: >
      podman run ghcr.io/noipcom/noip-duc:latest  -g all.ddnskey.com --username {{ dynDNSuser }} --password {{ dynDNSpwd }}
  
  - name: Wait for DNS 
    ansible.builtin.debug:
      msg: waiting for A record
    until: lookup('community.general.dig', ocservDNSName) == {{ ansible_default_ipv4.address }}
    retries: 60
    delay: 10

  - name: Enable and activate firewalld
    ansible.builtin.systemd_service:
      name: firewalld
      state: started
      enabled: true

  - name: Enable masquerade
    ansible.posix.firewalld:
      masquerade: true
      state: enabled
      permanent: true
      zone: public
      immediate: true

  - name: Open 443 port for ocserv
    ansible.posix.firewalld:
      port: 443
      state: enabled
      zone: public
      permanent: true
      immediate: true

  - name: Open 80 port for certbot
    ansible.posix.firewalld:
      port: 80
      state: enabled
      zone: public
      permanent: true  
      immediate: true

  - name: Debug challenges for certificate - dry run first
    ansible.builtin.shell: >
      /usr/bin/certbot certonly --standalone -d {{ ocservDNSName }} --debug-challenges --dry-run --non-interactive
    register: _challenges_res
    changed_when: "'The dry run was successful.' in _challenges_res"

  - name: Create certificate
    ansible.builtin.shell: >
      /usr/bin/certbot certonly --standalone --domains {{ ocservDNSName }} --non-interactive
    register: _issue_res
    changed_when: "'not yet due for renewal' or 'Successfully received certificate' in _issue_res"

  - name: Template ocserv.conf
    ansible.builtin.template:
      src: "{{ role_path }}/templates/ocserv.conf"
      dst: "/etc/ocserv/ocserv.conf"
      owner: "root"
      group: "root"
      mode: "0644"

  - name: Template ocpwd file
    ansible.builtin.template:
      src: "{{ role_path }}/templates/ocpasswd"
      dst: "/etc/ocserv/ocpasswd "
      owner: "root"
      group: "root"
      mode: "0600"

  - name: Enable and activate ocserv
    ansible.builtin.systemd_service:
      name: ocserv
      state: started
      enabled: true
